#!/bin/bash

#set wallpaper and directory variable
        dir="${HOME}/wallpapers"
	BG="$(find "$dir" -name '*.jpg' -o -name '*.png' -o -name '*.jpeg' -o -name '*.gif' | shuf -n1)"

# Picks background wallpaper
swww img $BG -t grow --transition-pos top --transition-duration 0.5 --transition-fps 60



# generate color scheme
wal -i $BG -q

# reload configs

pgrep kitty && pkill kitty && kitty
pgrep waybar && pkill waybar && waybar
pywalfox update
~/.config/mako/update-theme
#~/wallpapers/discordupdater #uncomment if you use the vesktop theme
#~/wallpapers/spicetifyupdater #uncomment if you use the spicetify theme, you can find it at https://github.com/Devedeu/spotify-pywal-theme
#~/.config/mako/update-theme #uncomment if you use any of the two above because sometimes mako won't update and I don't understand why so the solution was to run the script 2 times

